# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WageringRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=20)),
            ],
            options={
                'verbose_name': 'WageringRequirement Configuration',
            },
        ),
    ]
