# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:39
from __future__ import unicode_literals

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars')], default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Deposit Bonus', max_length=120)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=13)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.BonusWallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars')], default='EUR', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Login Bonus', max_length=120)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=13)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.BonusWallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('won', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars')], default='EUR', max_length=3)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.Wallet')),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.Wallet'),
        ),
    ]
