# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:49
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuswallet',
            options={'verbose_name': 'Bonus Wallet', 'verbose_name_plural': 'All Bonus Wallets'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit', 'verbose_name_plural': 'All Deposits'},
        ),
        migrations.AlterModelOptions(
            name='depositbonus',
            options={'verbose_name': 'Deposit Bonus', 'verbose_name_plural': 'DepositBonus given'},
        ),
        migrations.AlterModelOptions(
            name='loginbonus',
            options={'verbose_name': 'Login Bonus', 'verbose_name_plural': 'LoginBonus given'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'verbose_name': 'Users logins', 'verbose_name_plural': 'All users logins'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Real money Wallet', 'verbose_name_plural': 'Real money Wallets'},
        ),
        migrations.AlterModelOptions(
            name='withdrawn',
            options={'verbose_name': 'Withdraw', 'verbose_name_plural': 'Withdraws'},
        ),
        migrations.AddField(
            model_name='bonuswallet',
            name='bet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
        migrations.AddField(
            model_name='depositbonus',
            name='wagering_requirement',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='loginbonus',
            name='wagering_requirement',
            field=models.IntegerField(default=10),
        ),
    ]
