# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 21:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaming', '0002_auto_20171125_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='value',
            new_name='bonus',
        ),
        migrations.AddField(
            model_name='wallet',
            name='money',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13),
        ),
    ]
