# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 03:05
from __future__ import unicode_literals

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaming', '0002_auto_20171127_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawnBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.BonusWallet')),
            ],
            options={
                'verbose_name': 'Withdraw bonusmoney',
                'verbose_name_plural': 'Withdraws bonusmoney',
            },
        ),
        migrations.CreateModel(
            name='WithdrawnMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.Wallet')),
            ],
            options={
                'verbose_name': 'Withdraw money',
                'verbose_name_plural': 'Withdraws money',
            },
        ),
        migrations.RemoveField(
            model_name='withdrawn',
            name='wallet',
        ),
        migrations.DeleteModel(
            name='Withdrawn',
        ),
    ]
