# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igaming', '0003_auto_20171128_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawnbonus',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.Wallet'),
        ),
    ]
