# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:56
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('igaming', '0003_auto_20171126_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='bonus',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='money',
        ),
        migrations.AddField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'US Dollars')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='depositbonus',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.BonusWallet'),
        ),
        migrations.AlterField(
            model_name='loginbonus',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igaming.BonusWallet'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
